export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1df93b7f': [() => import(/* webpackChunkName: '1df93b7f' */ '@site/src/pages/index.tsx'), '@site/src/pages/index.tsx', require.resolveWeak('@site/src/pages/index.tsx')],
  '52e2a80b': [() => import(/* webpackChunkName: '52e2a80b' */ '@site/docs/readme.md'), '@site/docs/readme.md', require.resolveWeak('@site/docs/readme.md')],
  '59e891b0': [() => import(/* webpackChunkName: '59e891b0' */ '/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '72abb204': [() => import(/* webpackChunkName: '72abb204' */ '/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/zivl/github/countdown/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],};
